name: Build Prism.Maui

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build Prism.Maui
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: Setup .NET Core 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.300-preview.22204.3'
          include-prerelease: true

      - name: Install .NET MAUI Workload
        run: |
          dotnet workload install maui

      - name: NuGet Restore
        run: dotnet restore build.slnf

      - name: Build Packages
        run: dotnet build build.slnf -c Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: NuGet
          path: Artifacts/

  deploy-internal:
    name: Deploy Internal
    runs-on: windows-latest
    needs: build
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: NuGet
          path: Artifacts/

      - name: NuGet Publish (In-House)
        uses: dansiegel/publish-nuget@v1.01
        with:
            filename: 'Artifacts/*.nupkg'
            feedUrl: ${{ secrets.IN_HOUSE_NUGET_FEED }}
            apiKey: ${{ secrets.IN_HOUSE_API_KEY }}

  deploy-sponsors:
    name: Deploy Internal
    runs-on: windows-latest
    needs: build
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: NuGet
          path: Artifacts/

      - name: NuGet Publish (Sponsor Connect)
        uses: dansiegel/publish-nuget@v1.01
        with:
            filename: 'Artifacts/*.nupkg'
            feedUrl: ${{ secrets.SPONSOR_CONNECT_NUGET_FEED }}
            apiKey: ${{ secrets.SPONSOR_CONNECT_TOKEN }}
